### ISSUE TITLE
format numbers 

### ISSUE THREAD

**Issue by Azmah-Bad** [HugoCo/VaccinStats#1]
before printing numbers in the tweet it would be better and easier to read if there is a space between every 3 digits. 

example: 
current version: 186078 1ères doses ont été injectées (7742466 au total)
suggested : 186 078 1ères doses ont été injectées (7742466 au total)

Perhaps also  add emojis to the tweet 💉

🤙 HBA

**Comment by HugoCo** [comment]
corrected!
